/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import dataType.*;

/**
 *
 * @author Dito
 */
public class JDialog4205314159 extends javax.swing.JDialog {

    DaoPerpus205314159 dtPerpus;
    DefaultTableModel tabelModel;
    TableColumnModel columnModel;

    /**
     * Creates new form JDialog3
     */
    public JDialog4205314159(java.awt.Frame parent, boolean modal, DaoPerpus205314159 dtPerpus) throws SQLException {
        super(parent, modal);
        initComponents();

        this.dtPerpus = dtPerpus;
//        dtPerpus.fillData();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        simpanB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        majalahB = new javax.swing.JRadioButton();
        diskB = new javax.swing.JRadioButton();
        bukuB = new javax.swing.JRadioButton();
        resetB = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        formatTF = new javax.swing.JTextField();
        seriTF = new javax.swing.JTextField();
        isbnTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        judulTF = new javax.swing.JTextField();
        penerbitTF = new javax.swing.JTextField();
        tahunTerbTF = new javax.swing.JTextField();
        availCB = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 229, 207));
        jPanel1.setMaximumSize(new java.awt.Dimension(418, 360));
        jPanel1.setPreferredSize(new java.awt.Dimension(418, 360));

        jPanel2.setBackground(new java.awt.Color(247, 246, 242));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pendataan Koleksi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(247, 246, 242));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        simpanB.setText("Simpan");
        simpanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBActionPerformed(evt);
            }
        });

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        majalahB.setBackground(new java.awt.Color(247, 246, 242));
        buttonGroup1.add(majalahB);
        majalahB.setText("Majalah");
        majalahB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majalahBActionPerformed(evt);
            }
        });

        diskB.setBackground(new java.awt.Color(247, 246, 242));
        buttonGroup1.add(diskB);
        diskB.setSelected(true);
        diskB.setText("Disk");
        diskB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskBActionPerformed(evt);
            }
        });

        bukuB.setBackground(new java.awt.Color(247, 246, 242));
        buttonGroup1.add(bukuB);
        bukuB.setText("Buku");
        bukuB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukuBActionPerformed(evt);
            }
        });

        resetB.setText("Reset");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(247, 246, 242));
        jPanel4.setLayout(new java.awt.GridLayout(8, 1, 1, 5));

        jLabel6.setText("Format");
        jPanel4.add(jLabel6);

        jLabel8.setText("Seri");
        jLabel8.setEnabled(false);
        jPanel4.add(jLabel8);

        jLabel7.setText("ISBN");
        jPanel4.add(jLabel7);

        jLabel1.setText("ID Koleksi");
        jPanel4.add(jLabel1);

        jLabel3.setText("Judul");
        jPanel4.add(jLabel3);

        jLabel5.setText("Penerbit");
        jPanel4.add(jLabel5);

        jLabel9.setText("Tahun Terbit");
        jPanel4.add(jLabel9);

        jLabel4.setText("Status Pinjam");
        jPanel4.add(jLabel4);

        jPanel5.setBackground(new java.awt.Color(247, 246, 242));
        jPanel5.setLayout(new java.awt.GridLayout(8, 1, 1, 5));

        formatTF.setText("Audio/Video/Document");
        jPanel5.add(formatTF);

        seriTF.setEnabled(false);
        jPanel5.add(seriTF);
        jPanel5.add(isbnTF);

        idTF.setText("D");
        jPanel5.add(idTF);
        jPanel5.add(judulTF);
        jPanel5.add(penerbitTF);
        jPanel5.add(tahunTerbTF);

        availCB.setBackground(new java.awt.Color(247, 246, 242));
        availCB.setText("Not Available");
        availCB.setMargin(new java.awt.Insets(0, 0, 0, 0));
        availCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availCBActionPerformed(evt);
            }
        });
        jPanel5.add(availCB);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(resetB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(diskB)
                        .addGap(18, 18, 18)
                        .addComponent(majalahB)
                        .addGap(18, 18, 18)
                        .addComponent(bukuB)
                        .addGap(0, 585, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskB)
                    .addComponent(majalahB)
                    .addComponent(bukuB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetB)
                    .addComponent(simpanB)
                    .addComponent(cancelB)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diskBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskBActionPerformed
        // TODO add your handling code here:
        popUpLabelTF();
        // DISK
        jLabel6.setText("Format");
        formatTF.setText("Audio/Video/Document");
        jLabel7.setText("ISBN");
        idTF.setText("D");
    }//GEN-LAST:event_diskBActionPerformed

    private void majalahBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majalahBActionPerformed
        // TODO add your handling code here:
        popUpLabelTF();
        // MAJALAH
        jLabel6.setText("Volume");
        jLabel7.setText("ISSN");
        jLabel8.setText("Seri");
        formatTF.setText("");
        idTF.setText("M");
    }//GEN-LAST:event_majalahBActionPerformed

    private void bukuBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukuBActionPerformed
        // TODO add your handling code here:
        popUpLabelTF();
        // BUKU
        jLabel6.setText("Halaman");
        jLabel7.setText("ISBN");
        formatTF.setText("");
        idTF.setText("B");
    }//GEN-LAST:event_bukuBActionPerformed

    private void simpanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBActionPerformed
        // TODO add your handling code here:
        // BEGIN CODE INITIALIZE
        String format = formatTF.getText();
        String isbn = isbnTF.getText();
        String id = idTF.getText();
        String judul = judulTF.getText();
        String penerbit = penerbitTF.getText();
        String tahunTerbit = tahunTerbTF.getText();
        boolean status = availCB.isSelected();

        //BEGIN exception
        try {
            if (!(tahunTerbit.matches("\\d{4}"))) {
                throw new Exception("Please input 4 digits only in 'Tahun Terbit'");
            }
            if (!(id.matches("^[DBM]\\d+"))) {
                throw new Exception("Id Koleksi harus diawali D/B/M");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // END exception
        if (diskB.isSelected()) {
            Koleksi205314159 koleksiNew = new Cd205314159(id, judul, penerbit, tahunTerbit, status, isbn, format);
            isiData(koleksiNew);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!\n" + koleksiNew.toString(), "Information", JOptionPane.INFORMATION_MESSAGE);
        } else if (majalahB.isSelected()) {
            String seri = seriTF.getText();
            int volume, seriInt;
            try {
                volume = Integer.parseInt(format);
                seriInt = Integer.parseInt(seri);
                setDataInt(volume);
                setDataInt(seriInt);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "'"
                        + formatTF.getText() + " or " + seriTF.getText() + "' is invalid\n"
                        + "Please enter digits number only");
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                return;
            }
            Koleksi205314159 koleksiNew = new Majalah205314159(id, judul, penerbit, tahunTerbit, status, isbn, volume, seriInt);
            isiData(koleksiNew);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!\n" + koleksiNew.toString(), "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int jumHal;
            try {
                if (!(format.equalsIgnoreCase("Audio")) && !(format.equalsIgnoreCase("Video")) && !(format.equalsIgnoreCase("Document"))) {
                throw new Exception("Format harus Audio/Video/Document");
            }
                jumHal = Integer.parseInt(format);
                setDataInt(jumHal);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "'"
                        + formatTF.getText() + "' is invalid\n"
                        + "Please enter digits number only");
                return;
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                return;
            }
            Koleksi205314159 koleksiNew = new Buku205314159(id, judul, penerbit, tahunTerbit, status, isbn, jumHal);
            isiData(koleksiNew);
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!\n" + koleksiNew.toString(), "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        // END CODE
        // RESET
        resetBActionPerformed(evt);
        tampilData();
    }//GEN-LAST:event_simpanBActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        // TODO add your handling code here:
        judulTF.setText("");
        idTF.setText("");
        penerbitTF.setText("");
        formatTF.setText("");
        isbnTF.setText("");
        availCB.setSelected(false);
        seriTF.setText("");
        tahunTerbTF.setText("");
    }//GEN-LAST:event_resetBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        int a = jTable1.getSelectedRow();
        if (a == -1) {} else {
            Koleksi205314159 delete = dtPerpus.koleksiList.get(a);
            if(delete instanceof Buku205314159){
                dtPerpus.deleteDataKoleksi(delete.getId_koleksi(), "buku");
            } else if (delete instanceof Cd205314159){
                dtPerpus.deleteDataKoleksi(delete.getId_koleksi(), "dvd");
            } else {
                dtPerpus.deleteDataKoleksi(delete.getId_koleksi(), "majalah");
            }
        }
        resetBActionPerformed(evt);
        tampilData();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void availCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availCBActionPerformed

    /**
     * @param args the command line arguments/
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog4205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog4205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog4205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog4205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog4 dialog = new JDialog4(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog4 dialog = new JDialog4(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog4205314159 dialog = new JDialog4205314159(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog4205314159 dialog = new JDialog4205314159(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    //method tambahan
    public void setDataInt(int data) throws Exception {
        if (data > 0) {
            //tf.setText(String.valueOf(data));
        } else {
            throw new NegativeValueException(
                    "Input must be greater than 0");
        }
    }

    class NegativeValueException extends Exception {

        public NegativeValueException() {
        }

        public NegativeValueException(String message) {
            super(message);
        }
    }

    //cd String id_koleksi, String judul, String penerbit, String tahun_terbit, boolean status, String isbn, String format  -   8
    //majalah String id_koleksi, String judul, String penerbit, String tahun_terbit, boolean status, String issn, int volume, int series - 9   
    //buku String id_koleksi, String judul, String penerbit, String tahun_terbit, boolean status, String isbn, int jum_halaman  -   8
    public void tampilData() {
        String[] kolom = {"Tipe", "Id", "Judul", "Penerbit", "Tahun Terbit", "Available", "ISBN/ISSN", "Format/Vol/JumHal", "Series"};
        Object[][] objData = new Object[dtPerpus.koleksiList.size()][9]; // 4 merupakan jumlah kolom
        int i = 0;
        for (Koleksi205314159 n : dtPerpus.koleksiList) {
            String status;
            if (!n.isStatusPinjam()) {
                status = "Yes";
            } else {
                status = "No";
            }
            if (n instanceof Cd205314159) {
                String[] arrData = {"CD", n.getId_koleksi(), n.getJudul(), n.getPenerbit(), n.getTahun_terbit(), status,
                    ((Cd205314159) n).getIsbn(), ((Cd205314159) n).getFormat(), "-"};
                objData[i] = arrData;
            } else if (n instanceof Majalah205314159) {
                String[] arrData = {"Majalah", n.getId_koleksi(), n.getJudul(), n.getPenerbit(), n.getTahun_terbit(), status,
                    ((Majalah205314159) n).getIssn(), Integer.toString(((Majalah205314159) n).getVolume()), Integer.toString(((Majalah205314159) n).getSeries())};
                objData[i] = arrData;
            } else {
                String[] arrData = {"Buku", n.getId_koleksi(), n.getJudul(), n.getPenerbit(), n.getTahun_terbit(), status,
                    ((Buku205314159) n).getIsbn(), Integer.toString(((Buku205314159) n).getJum_halaman()), "-"};
                objData[i] = arrData;
            }
            i++;
        }
        tabelModel = new DefaultTableModel(objData, kolom) {
            //membuat tabel tidak bisa diedit saat diklik
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jTable1.setModel(tabelModel);
        columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(200);
        columnModel.getColumn(4).setPreferredWidth(150);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(200);
        columnModel.getColumn(7).setPreferredWidth(250);
        columnModel.getColumn(8).setPreferredWidth(100);
    }
    
    public void isiData(Koleksi205314159 kol) {
        dtPerpus.isiDataKoleksi(kol);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox availCB;
    private javax.swing.JRadioButton bukuB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelB;
    private javax.swing.JRadioButton diskB;
    private javax.swing.JTextField formatTF;
    private javax.swing.JTextField idTF;
    private javax.swing.JTextField isbnTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judulTF;
    private javax.swing.JRadioButton majalahB;
    private javax.swing.JTextField penerbitTF;
    private javax.swing.JButton resetB;
    private javax.swing.JTextField seriTF;
    private javax.swing.JButton simpanB;
    private javax.swing.JTextField tahunTerbTF;
    // End of variables declaration//GEN-END:variables

    public void popUpLabelTF() {
        if (majalahB.isSelected()) {
            seriTF.setEnabled(true);
            jLabel8.setEnabled(true);
        } else {
            seriTF.setText("");
            seriTF.setEnabled(false);
            jLabel8.setEnabled(false);
        }
    }

}
