/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import dataType.*;

/**
 *
 * @author Dito
 */
public class JDialog3205314159 extends javax.swing.JDialog {

    DaoPerpus205314159 dtPerpus;
    DefaultTableModel tabelModel;
    TableColumnModel columnModel;

    /**
     * Creates new form JDialog3
     */
    public JDialog3205314159(java.awt.Frame parent, boolean modal, DaoPerpus205314159 dtPerpus) throws SQLException {
        super(parent, modal);
        initComponents();

        this.dtPerpus = dtPerpus;
//        dtPerpus.fillData();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        simpanB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mhsB = new javax.swing.JRadioButton();
        umumB = new javax.swing.JRadioButton();
        dosenB = new javax.swing.JRadioButton();
        namaTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomorTF = new javax.swing.JTextField();
        resetB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTA = new javax.swing.JTextArea();
        maksPinjamTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form");
        setMinimumSize(new java.awt.Dimension(418, 350));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(240, 229, 207));

        jPanel2.setBackground(new java.awt.Color(247, 246, 242));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pendataan Peminjam");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(247, 246, 242));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        simpanB.setText("Simpan");
        simpanB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBActionPerformed(evt);
            }
        });

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Peminjam");

        jLabel3.setText("Nama");

        jLabel5.setText("Alamat");

        mhsB.setBackground(new java.awt.Color(247, 246, 242));
        buttonGroup1.add(mhsB);
        mhsB.setText("Mahasiswa");
        mhsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsBActionPerformed(evt);
            }
        });

        umumB.setBackground(new java.awt.Color(247, 246, 242));
        buttonGroup1.add(umumB);
        umumB.setSelected(true);
        umumB.setText("Umum");
        umumB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umumBActionPerformed(evt);
            }
        });

        dosenB.setBackground(new java.awt.Color(247, 246, 242));
        buttonGroup1.add(dosenB);
        dosenB.setText("Dosen");
        dosenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosenBActionPerformed(evt);
            }
        });

        idTF.setText("U");

        jLabel6.setText("NIK");

        resetB.setText("Reset");
        resetB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBActionPerformed(evt);
            }
        });

        alamatTA.setColumns(20);
        alamatTA.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        alamatTA.setRows(2);
        alamatTA.setMaximumSize(new java.awt.Dimension(164, 94));
        alamatTA.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setViewportView(alamatTA);
        alamatTA.getAccessibleContext().setAccessibleParent(jPanel3);

        jLabel7.setText("Maks Pinjam");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idTF)
                            .addComponent(nomorTF)
                            .addComponent(namaTF)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                            .addComponent(maksPinjamTF)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(resetB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelB))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(umumB)
                                .addGap(18, 18, 18)
                                .addComponent(mhsB)
                                .addGap(18, 18, 18)
                                .addComponent(dosenB))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umumB)
                    .addComponent(mhsB)
                    .addComponent(dosenB))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nomorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maksPinjamTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetB)
                    .addComponent(simpanB)
                    .addComponent(cancelB)
                    .addComponent(jButton1))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umumBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umumBActionPerformed
        // TODO add your handling code here:
        // UMUM
        jLabel6.setText("NIK");
        idTF.setText("U");
    }//GEN-LAST:event_umumBActionPerformed

    private void mhsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsBActionPerformed
        // TODO add your handling code here:
        // MAHASISWA
        jLabel6.setText("NIM");
        idTF.setText("M");
    }//GEN-LAST:event_mhsBActionPerformed

    private void dosenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosenBActionPerformed
        // TODO add your handling code here:
        // DOSEN
        jLabel6.setText("NIP");
        idTF.setText("D");
    }//GEN-LAST:event_dosenBActionPerformed

    private void simpanBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBActionPerformed
        // TODO add your handling code here:
        // BEGIN CODE INITIALIZE
        String nomor = nomorTF.getText();
        String id = idTF.getText();
        String nama = namaTF.getText();
        String alamat = alamatTA.getText();
        int maksPinjam;

        // BEGIN exception handling
        try {
            maksPinjam = Integer.parseInt(maksPinjamTF.getText());
            setMaksPinj(maksPinjam);

            if (!(id.matches("^[MDU]\\d+"))) {
                throw new Exception("ID harus diawali M/D/U!");
            }
            if (nama.matches(".*\\d.*")) {
                throw new Exception("Nama anda mengandung angka: " + nama);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "'"
                    + maksPinjamTF.getText() + "' is invalid\n"
                    + "Please enter digits number only", "ERROR", JOptionPane.WARNING_MESSAGE);
            return;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // END exception handling
        // BEGIN input data to Table
        try {
            if (umumB.isSelected()) {
                Peminjam205314159 peminjamNew = new MasyarakatUmum205314159(id, nama, alamat, maksPinjam, nomor);
                if (isiData(peminjamNew)) {
                    JOptionPane.showMessageDialog(this, "Data MasyarakatUmum berhasil disimpan!\n" + peminjamNew.toString(), "Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    return;
                }
            } else if (mhsB.isSelected()) {
                Peminjam205314159 peminjamNew = new Mahasiswa205314159(id, nama, alamat, maksPinjam, nomor);
                if (isiData(peminjamNew)) {
                    JOptionPane.showMessageDialog(this, "Data Mahasiswa berhasil disimpan!\n" + peminjamNew.toString(), "Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    return;
                }
            } else {
                Peminjam205314159 peminjamNew = new Dosen205314159(id, nama, alamat, maksPinjam, nomor);
                if (isiData(peminjamNew)) {
                    JOptionPane.showMessageDialog(this, "Data Dosen berhasil disimpan!\n" + peminjamNew.toString(), "Information", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    return;
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        // END input data to Table
        // END CODE INITIALIZE
        // RESET
        tampilData();
        resetBActionPerformed(evt);
    }//GEN-LAST:event_simpanBActionPerformed

    private void resetBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            int a = jTable1.getSelectedRow();
            if (a == -1) {
            } else {
                Peminjam205314159 delete = dtPerpus.peminjamList.get(a);
                if (delete instanceof Dosen205314159) {
                    dtPerpus.deleteDataPeminjam(delete.getId(), "Dosen");
                } else if (delete instanceof Mahasiswa205314159) {
                    dtPerpus.deleteDataPeminjam(delete.getId(), "Mahasiswa");
                } else {
                    dtPerpus.deleteDataPeminjam(delete.getId(), "Umum");
                }
            }
            resetBActionPerformed(evt);
            tampilData();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // EDIT DATA
        try {
            simpanB.setText("Update");
            int a = jTable1.getSelectedRow();
            if (a == -1) {
            } else {
                Peminjam205314159 pemOld = dtPerpus.peminjamList.get(a);   //old
                String notf = "";
                if (pemOld instanceof Dosen205314159) {
                    notf = ((Dosen205314159) pemOld).getNip();
                    dosenB.setSelected(true);
                } else if (pemOld instanceof Mahasiswa205314159) {
                    notf = ((Mahasiswa205314159) pemOld).getNo_mhs();
                    mhsB.setSelected(true);
                } else {
                    notf = ((MasyarakatUmum205314159) pemOld).getNo_ktp();
                    umumB.setSelected(true);
                }
                //show on textField
                namaTF.setText(pemOld.getNama());
                idTF.setText(pemOld.getId());
                nomorTF.setText(notf);
                alamatTA.setText(pemOld.getAlamat());
                maksPinjamTF.setText(String.valueOf(pemOld.getMaxPinjam()));
                //edit pemNew to pemOld (input)
//                Peminjam205314159 pemNew = 
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog3205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog3205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog3205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog3205314159.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog3 dialog = new JDialog3(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog3 dialog = new JDialog3(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog3205314159 dialog = new JDialog3205314159(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialog3205314159 dialog = new JDialog3205314159(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
    }

    //method tambahan
    public void setMaksPinj(int max) throws Exception {
        if (max > 0) {
            //maksPinjamTF.setText(String.valueOf(max));
        } else {
            throw new NegativeValueException(
                    "Input Maks Pinjam must be greater than 0");
        }
    }

    class NegativeValueException extends Exception {

        public NegativeValueException() {
        }

        public NegativeValueException(String message) {
            super(message);
        }
    }

    //String id, String nama, String alamat, int maxPinjam, String nip, TIPE OBJECT = 6 kolom
    public void tampilData() {
        String[] kolom = {"Tipe", "Nomor", "Id", "Nama", "Alamat", "Max Pinjam"};
        Object[][] objData = new Object[dtPerpus.peminjamList.size()][6]; // 4 merupakan jumlah kolom
        int i = 0;
        for (Peminjam205314159 n : dtPerpus.peminjamList) {
            if (n instanceof Dosen205314159) {
                String[] arrData = {"Dosen", ((Dosen205314159) n).getNip(), n.getId(), n.getNama(), n.getAlamat(), Integer.toString(n.getMaxPinjam())};
                objData[i] = arrData;
            } else if (n instanceof Mahasiswa205314159) {
                String[] arrData = {"Mahasiswa", ((Mahasiswa205314159) n).getNo_mhs(), n.getId(), n.getNama(), n.getAlamat(), Integer.toString(n.getMaxPinjam())};
                objData[i] = arrData;
            } else {
                String[] arrData = {"Umum", ((MasyarakatUmum205314159) n).getNo_ktp(), n.getId(), n.getNama(), n.getAlamat(), Integer.toString(n.getMaxPinjam())};
                objData[i] = arrData;
            }
            i++;
        }
        tabelModel = new DefaultTableModel(objData, kolom) {
            //membuat tabel tidak bisa diedit saat diklik
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jTable1.setModel(tabelModel);
        columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(150);
        columnModel.getColumn(1).setPreferredWidth(300);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(300);
        columnModel.getColumn(4).setPreferredWidth(300);
        columnModel.getColumn(5).setPreferredWidth(150);
    }

    public boolean isiData(Peminjam205314159 pem) throws SQLException {
        if (umumB.isSelected()) { //masyarakat umum
            if (!((MasyarakatUmum205314159) pem).getNo_ktp().matches("\\d{16}")) {
                JOptionPane.showMessageDialog(this, "NIK harus 16 digit!\n", "ERROR", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } else if (mhsB.isSelected()) {  //mahasiswa
            if (!((Mahasiswa205314159) pem).getNo_mhs().matches("\\d{9}")) {
                JOptionPane.showMessageDialog(this, "NIM harus 9 digit!\n", "ERROR", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } else {    //dosen
            if (!((Dosen205314159) pem).getNip().matches("\\d{18}")) {
                JOptionPane.showMessageDialog(this, "NIP harus 18 digit!\n", "ERROR", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        //method normal
//        dtPerpus.peminjamList.add(pem);
        //menggunakan db
        
        boolean update = false;
        for (Peminjam205314159 peminjam : dtPerpus.peminjamList) {
            if(peminjam.getId().equals(pem.getId()))
                update = true;
        }
        if (update) {
            dtPerpus.updatePeminjam(pem);
        } else {
            dtPerpus.isiDataPeminjam(pem);
        }

        return true;
    }

    public void reset() {
        namaTF.setText("");
        idTF.setText("");
        nomorTF.setText("");
        alamatTA.setText("");
        maksPinjamTF.setText("");
        
        simpanB.setText("Simpan");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelB;
    private javax.swing.JRadioButton dosenB;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField maksPinjamTF;
    private javax.swing.JRadioButton mhsB;
    private javax.swing.JTextField namaTF;
    private javax.swing.JTextField nomorTF;
    private javax.swing.JButton resetB;
    private javax.swing.JButton simpanB;
    private javax.swing.JRadioButton umumB;
    // End of variables declaration//GEN-END:variables
}
